-- AlterTable
ALTER TABLE "StoreSettings" ADD COLUMN IF NOT EXISTS "brandColorYou" TEXT NOT NULL DEFAULT '#2563EB';
ALTER TABLE "StoreSettings" ADD COLUMN IF NOT EXISTS "brandColorPosh" TEXT NOT NULL DEFAULT '#DC2626';
ALTER TABLE "StoreSettings" ADD COLUMN IF NOT EXISTS "brandColorCart" TEXT NOT NULL DEFAULT '#2563EB';
